import Navbar from "@/components/Navigation"
import Footer from "@/components/Footer"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Navbar />
      {children}
      <Footer />
      
    </html>
  )
}
